version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/GraphEngine"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/GraphEngine.Tests"
    schedule:
      interval: "daily"
